# -*- coding: utf-8 -*-

# This file is part of thumbor-wand-engine
# https://github.com/scorphus/thumbor-wand-engine

# Licensed under the MIT license:
# http://www.opensource.org/licenses/mit-license
# Copyright (c) 2020-2021, Pablo S. Blum de Aguiar <scorphus@gmail.com>

[tool.black]
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.tox
    | thumbor
    | thumbor_integration_tests
  )/
)
'''
